import type { NextPage } from "next";
import Head from "next/head";
import {
  GetStaticPaths,
  GetStaticProps,
  InferGetStaticPropsType,
} from "next/types";

import { Box } from "theme-ui";

import Lottie from "react-lottie";
import loading from "../resources/animated-cubes.json";
import TopMenu from "../components/TopMenu/TopMenu";
import { getAllProducts, getProductBySlug } from "../lib/api";
import { IProduct } from "../lib/product.type";

export default function Home({ products }: { products: Array<IProduct> }) {
  return (
    <Box sx={{ backgroundColor: "tertiaryScale.8" }}>
      <Head>
        <title>eShopU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopMenu products={products} />
        <Lottie options={{ animationData: loading, loop: true }} width={200} />
      </main>

      <footer></footer>
    </Box>
  );
}

export const getStaticProps: GetStaticProps = async ({
  params,
  preview = false,
}) => {
  const data: Array<IProduct> = await getAllProducts();

  return {
    props: {
      preview,
      products: data,
    },
  };
};
