import type { NextPage } from "next";
import Head from "next/head";

import { Box } from "theme-ui";

import Lottie from "react-lottie";
import loading from "../resources/animated-cubes.json";
import TopMenu from "../components/TopMenu/TopMenu";

const Home: NextPage = () => {
  const navigations = [
    { title: "Categories", links: ["IT", "Games", "Teddybears"] },
    { title: "Best sellers", links: ["Rainbow teddy"] },
  ];

  return (
    <Box sx={{ backgroundColor: "tertiaryScale.8" }}>
      <Head>
        <title>Shoup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopMenu navigations={navigations} />
        <Lottie options={{ animationData: loading, loop: true }} width={200} />
      </main>

      <footer></footer>
    </Box>
  );
};

export default Home;
