import type { NextPage } from "next";
import Head from "next/head";

import { Box, Flex } from "theme-ui";

import Logo from "../components/TopMenu/Logo";
import TopMenuLink from "../components/TopMenu/TopMenuItem";

import Lottie from "react-lottie";
import loading from "../resources/animated-cubes.json";
import TopMenuContainer from "../components/TopMenu/TopMenuContainer";
import TopMenuList from "../components/TopMenu/TopMenuList";

const Home: NextPage = () => {
  const navigations = [
    { title: "Categories", links: ["IT", "Games", "Teddybears"] },
    { title: "Best sellers", links: ["Rainbow teddy"] },
  ];

  return (
    <Box sx={{ backgroundColor: "tertiaryScale.8" }}>
      <Head>
        <title>Shoup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex
          as="nav"
          sx={{
            padding: "3xs",
            backgroundColor: "tertiaryScale.7",
            alignItems: "center",
            gap: "md",
          }}
        >
          <Box sx={{ padding: "sm" }}>
            <Logo height={40} width={40} />
          </Box>
          <Flex as="ul" sx={{ listStyle: "none", padding: 0, gap: "2xs" }}>
            {navigations.map((navigation) => {
              return (
                <TopMenuContainer
                  key={navigation.title}
                  title={navigation.title}
                >
                  <TopMenuList links={navigation.links} />
                </TopMenuContainer>
              );
            })}
          </Flex>
        </Flex>
        <Lottie options={{ animationData: loading, loop: true }} width={200} />
      </main>

      <footer></footer>
    </Box>
  );
};

export default Home;
